/* === GAMES DATA === */
const games = [
  { name:"Basket Allstars", category:["Sport", "Basketball Games", "Multiplayer Games"], image:"images/gameicons/basketball allstars.jpg", link:"basketball allstars.html"},
  { name:"Bird Sniper 2 Demo", category:["Action Games", "Shooting Games"], image:"images/gameicons/Bird Sniper 2 Demo.webp", link:"Bird Sniper 2 Demo.html"},
  { name:"Bulb connector", category:["Puzzle"], image:"images/gameicons/Bulb connector.webp", link:"Bulb connector.html"},
  { name:"Cat Bubble Shooter", category:["Shooting Games"], image:"images/gameicons/Cat Bubble Shooter.webp", link:"Cat Bubble Shooter.html"},
  { name:"chess multiplayer", category:["Multiplayer Games", "Board Games", "Strategy Games"], image:"images/gameicons/chess multiplayer.jpg", link:"chess multiplayer.html"},
  { name:"Chill Guy Candy Crush", category:["Chill Guy Games"], image:"images/gameicons/candycrushicon.png", link:"candycrush.html"},
  { name:"Chill Guy Crossy Road", category:["Chill Guy Games"], image:"images/gameicons/crossyicon.png", link:"crossy.html"},
  { name:"Chill Guy Flappy", category:["Chill Guy Games"], image:"images/gameicons/flappyicon.png", link:"flappy.html"},
  { name:"Chill Guy Jumper", category:["Chill Guy Games"], image:"images/gameicons/timicon.png", link:"jumper.html"},
  { name:"Chill Guy Shooter", category:["Chill Guy Games", "Shooting Games"], image:"images/gameicons/gijsicon.png", link:"gijs.html"},
  { name:"Chill Guy Snake", category:["Chill Guy Games", "Snake Games"], image:"images/gameicons/snakeicon.png", link:"snake.html"},
  { name:"Chill Guy Tetris", category:["Chill Guy Games"], image:"images/gameicons/tetrisicon.png", link:"tetris.html"},
  { name:"Dinosaur", category:["."], image:"images/gameicons/dinosaur-game.jpg", link:"dinosaur.html"},
  { name:"Dodge Clicker", category:["Idle Games"], image:"images/gameicons/Doge Clicker.webp", link:"Doge Clicker.html"},
  { name:"Donkey Kong", category:["Monkey Games", "Action Games"], image:"images/gameicons/donkey-kong.jpg", link:"donkey-kong.html"},
  { name:"Doodle Champion Island", category:["Sport"], image:"images/gameicons/doodle-champion-island.jpg", link:"island.html"},
  { name:"Drunken Boxing", category:["Sport", "Boxing Games", "Multiplayer Games"], image:"images/gameicons/drunken boxing.jpg", link:"drunken boxing.html"},
  { name:"Fall Guys", category:["Multiplayer Games", "Parkour Games"], image:"images/gameicons/fall guys.jpg", link:"fall guys.html"},
  { name:"Fill the cup", category:["Puzzle"], image:"images/gameicons/Fill the cup.webp", link:"Fill the cup.html"},
  { name:"fireboy and watergirl", category:["Multiplayer Games"], image:"images/gameicons/fireboy and watergirl.jpg", link:"fireboy and watergirl.html"},
  { name:"Flappy Bird", category:["."], image:"images/gameicons/flappy-bird.jpg1.jpeg", link:"flappybird.html"},
  { name:"Galactic Wars", category:["War Games"], image:"images/gameicons/Galactic Wars.webp", link:"Galactic Wars.html"},
  { name:"Geometry Dash", category:["."], image:"images/gameicons/geometry-dash.jpg", link:"dash.html"},
  { name:"goal io", category:["Football Games", "Sport", "io games"], image:"images/gameicons/goal io.jpg", link:"goal io.html"},
  { name:"Gorilla Multiplayer", category:["Multiplayer Games", "Monkey Games"], image:"images/gameicons/gorilla multiplayer.jpg", link:"gorilla multiplayer.html"},
  { name:"Helix jump", category:["Parkour Games"], image:"images/gameicons/Helix jump.webp", link:"Helix jump.html"},
  { name:"Kill Baby Hitler", category:["Hitler", "Action Games"], image:"images/gameicons/Kill Baby Hitler.webp", link:"Kill Baby Hitler.html"},
  { name:"Mathai's Tea Shop", category:["Idle Games", "Shop"], image:"images/gameicons/Mathai's Tea Shop.webp", link:"Mathai's Tea Shop.html"},
  { name:"Monkey Mart", category:["Idle Games", "Shop", "Monkey Games"], image:"images/gameicons/monkey-mart.jpg", link:"monkey.html"},
  { name:"noob vs pro lava", category:["Multiplayer Games", "Parkour Games", "Minecraft"], image:"images/gameicons/noob vs pro lava.jpg", link:"noob vs pro lava.html"},
  { name:"PacFruit Ninjaman", category:["Action Games"], image:"images/gameicons/Fruit Ninja.webp", link:"Fruit Ninja.html"},
  { name:"Pacman", category:["."], image:"images/gameicons/pacman.png", link:"pacman.html"},
  { name:"paper io", category:["io games"], image:"images/gameicons/paper io.jpg", link:"paper io.html"},
  { name:"Poker", category:["Multiplayer Games", "Gambling Games"], image:"images/gameicons/poker.jpg", link:"poker.html"},
  { name:"Retro Bowl", category:["Sport"], image:"images/gameicons/retro-bowl.jpg", link:"retro.html"},
  { name:"Russian Knife Roulette Game", category:["Action Games"], image:"images/gameicons/Russian Knife Roulette Game.webp", link:"Russian Knife Roulette Game.html"},
  { name:"Scary Granny", category:["Horror"], image:"images/gameicons/scary granny.jpg", link:"scary granny.html"},
  { name:"Slope", category:["."], image:"images/gameicons/slope-game.jpg", link:"slope.html"},
  { name:"Sudoku challenge", category:["Puzzle"], image:"images/gameicons/Sudoku challenge.webp", link:"Sudoku challenge.html"},
  { name:"The Life Of Happy Stoner", category:["Stoner"], image:"images/gameicons/The Life Of Happy Stoner.webp", link:"The Life Of Happy Stoner.html"},
  { name:"Trolling Indian Scammers", category:["."], image:"images/gameicons/Trolling Indian Scammers.webp", link:"Trolling Indian Scammers.html"},
  { name:"Weed Smoking Simulator", category:["Stoner"], image:"images/gameicons/Weed Smoking Simulator.webp", link:"Weed Smoking Simulator.html"},
  { name:"Where in Space is Baby Hitler", category:["Hitler", "Action Games"], image:"images/gameicons/Where in Space is Baby Hitler.webp", link:"Where in Space is Baby Hitler.html"},
  { name:"World Dictator", category:["."], image:"images/gameicons/World Dictator.webp", link:"World Dictator.html"},
  { name:"Worms Zone a Slithery Snake", category:["Snake Games", "io games"], image:"images/gameicons/Worms Zone a Slithery Snake.jpg", link:"Worms Zone a Slithery Snake.html"},
  { name:"Block Blast Master", category:["."], image:"images/gameicons/Block Blast Master.avif", link:"Block Blast Master.html"},
  { name:"Brawl Simulator 3D", category:["."], image:"images/gameicons/Brawl Simulator 3D.avif", link:"Brawl Simulator 3D.html"},
  { name:"Deadly Descent", category:["."], image:"images/gameicons/Deadly Descent.avif", link:"Deadly Descent.html"},
  { name:"Fruit Merge: Juicy Drop Game", category:["."], image:"images/gameicons/Fruit Merge: Juicy Drop Game.avif", link:"Fruit Merge: Juicy Drop Game.html"},
  { name:"Golf Orbit", category:["."], image:"images/gameicons/Golf Orbit.avif", link:"Golf Orbit.html"},
  { name:"Hidden Object: Clues and Mysteries", category:["."], image:"images/gameicons/Hidden Object: Clues and Mysteries.avif", link:"Hidden Object: Clues and Mysteries.html"},
  { name:"Idle Tower Defense", category:["."], image:"images/gameicons/Idle Tower Defense.avif", link:"Idle Tower Defense.html"},
  { name:"Moto X3M Spooky Land", category:["."], image:"images/gameicons/Moto X3M Spooky Land.avif", link:"Moto X3M Spooky Land.html"},        
  { name:"Moto X3M", category:["."], image:"images/gameicons/Moto X3M.avif", link:"Moto X3M.html"},
  { name:"Skyblock 3D: Survival", category:["."], image:"images/gameicons/Skyblock 3D: Survival.avif", link:"Skyblock 3D: Survival.html"},

];