/* === GAMES DATA === */
const games = [
  { name:"Chill Guy Candy Crush", category:["Chill Guy Games"], image:"images/gameicons/candycrushicon.png", link:"candycrush.html"},
  { name:"Chill Guy Crossy Road", category:["Chill Guy Games"], image:"images/gameicons/crossyicon.png", link:"crossy.html"},
  { name:"Chill Guy Flappy", category:["Chill Guy Games"], image:"images/gameicons/flappyicon.png", link:"flappy.html"},
  { name:"Chill Guy Jumper", category:["Chill Guy Games"], image:"images/gameicons/timicon.png", link:"jumper.html"},
  { name:"Chill Guy Shooter", category:["Chill Guy Games", "Shooting Games"], image:"images/gameicons/gijsicon.png", link:"gijs.html"},
  { name:"Chill Guy Snake", category:["Chill Guy Games", "Snake Games"], image:"images/gameicons/snakeicon.png", link:"snake.html"},
  { name:"Chill Guy Tetris", category:["Chill Guy Games"], image:"images/gameicons/tetrisicon.png", link:"tetris.html"},
  { name:"Slope", category:["."], image:"images/gameicons/slope-game.jpg", link:"slope.html"},
  { name:"Geometry Dash", category:["."], image:"images/gameicons/geometry-dash.jpg", link:"dash.html"},
  { name:"Monkey Mart", category:["Idle Games", "Shop", "Monkey Games"], image:"images/gameicons/monkey-mart.jpg", link:"monkey.html"},
  { name:"Worms Zone a Slithery Snake", category:["Snake Games", "io games"], image:"images/gameicons/Worms Zone a Slithery Snake.jpg", link:"Worms Zone a Slithery Snake.html"},
  { name:"paper io", category:["io games"], image:"images/gameicons/paper io.jpg", link:"paper io.html"},
  { name:"Golf Orbit", category:["Sport", "Golf"], image:"images/gameicons/Golf Orbit.avif", link:"Golf Orbit.html"},
  { name:"Hazmob FPS: Online Shooter", category:["Action Games", "Shooting Games"], image:"images/gameicons/Hazmob FPS: Online Shooter.avif", link:"Hazmob FPS: Online Shooter.html"},
  { name:"Idle Tower Defense", category:["Idle Games", "Strategy Games", "Action Games"], image:"images/gameicons/Idle Tower Defense.avif", link:"Idle Tower Defense.html"},
  { name:"Moto X3M Spooky Land", category:["Racing", "Moto X3M"], image:"images/gameicons/Moto X3M Spooky Land.avif", link:"Moto X3M Spooky Land.html"},        
  { name:"Moto X3M", category:["Racing", "Moto X3M"], image:"images/gameicons/Moto X3M.avif", link:"Moto X3M.html"},
  { name:"Basket Allstars", category:["Sport", "Basketball Games", "Multiplayer Games"], image:"images/gameicons/basketball allstars.jpg", link:"basketball allstars.html"},
  { name:"Retro Bowl", category:["Sport"], image:"images/gameicons/retro-bowl.jpg", link:"retro.html"},
  { name:"Pacman", category:["."], image:"images/gameicons/pacman.png", link:"pacman.html"},
  { name:"Block Blast Master", category:["Puzzle"], image:"images/gameicons/Block Blast Master.avif", link:"Block Blast Master.html"},
  { name:"Brawl Simulator 3D", category:["Shooting Games", "Action Games"], image:"images/gameicons/Brawl Simulator 3D.avif", link:"Brawl Simulator 3D.html"},
  { name:"Deadly Descent", category:["Racing"], image:"images/gameicons/Deadly Descent.avif", link:"Deadly Descent.html"},
  { name:"Fruit Merge: Juicy Drop Game", category:["Fruit", "Puzzle"], image:"images/gameicons/Fruit Merge: Juicy Drop Game.avif", link:"Fruit Merge: Juicy Drop Game.html"},
  { name:"Skyblock 3D: Survival", category:["Minecraft"], image:"images/gameicons/Skyblock 3D: Survival.avif", link:"Skyblock 3D: Survival.html"},
  { name:"Age of Tanks Warriors: TD War", category:["War Games", "Strategy Games"], image:"images/gameicons/Age of Tanks Warriors: TD War.avif", link:"Age of Tanks Warriors: TD War.html"},
  { name:"Build and Fly Obby", category:["Obby"], image:"images/gameicons/Build and Fly Obby.avif", link:"Build and Fly Obby.html"},
  { name:"Escape Tsunami for Brainrots", category:["Obby"], image:"images/gameicons/Escape Tsunami for Brainrots.avif", link:"Escape Tsunami for Brainrots.html"},
  { name:"Gym Simulator Online, Escape", category:["Obby", "Sport"], image:"images/gameicons/Gym Simulator Online, Escape.avif", link:"Gym Simulator Online, Escape.html"},
  { name:"Hidden Object: Clues and Mysteries", category:["Puzzle", "Hidden Object"], image:"images/gameicons/Hidden Object: Clues and Mysteries.avif", link:"Hidden Object: Clues and Mysteries.html"},
  { name:"Hidden Objects: Island Secrets", category:["Puzzle", "Hidden Object"], image:"images/gameicons/Hidden Objects: Island Secrets.avif", link:"Hidden Objects: Island Secrets.html"},
  { name:"Obby: Climb and Slide", category:["Obby"], image:"images/gameicons/Obby: Climb and Slide.avif", link:"Obby Climb and Slide.html"},
  { name:"Speed per Click: Obby", category:["Obby"], image:"images/gameicons/Speed per Click: Obby.avif", link:"Speed per Click: Obby.html"},
  { name:"Stickman Kombat 2D", category:["Action Games", "Fight Game"], image:"images/gameicons/Stickman Kombat 2D.avif", link:"Stickman Kombat 2D.html"},
  { name:"Your Obby Escape", category:["Obby"], image:"images/gameicons/Your Obby Escape.avif", link:"Your Obby Escape.html"},
  { name:"AOD - Art Of Defense", category:["Defense Game", "Strategy Games"], image:"images/gameicons/AOD - Art Of Defense.avif", link:"AOD - Art Of Defense.html"},
  { name:"Bubble Boom", category:["Shooting Games"], image:"images/gameicons/Bubble Boom.avif", link:"Bubble Boom.html"},
  { name:"Build a Rollercoaster: Simulator", category:["Obby"], image:"images/gameicons/Build a Rollercoaster: Simulator.avif", link:"Build a Rollercoaster: Simulator.html"},
  { name:"Car Collision Master", category:["Racing"], image:"images/gameicons/Car Collision Master.avif", link:"Car Collision Master.html"},
  { name:"Cooking Empire", category:["Cooking"], image:"images/gameicons/Cooking Empire.avif", link:"Cooking Empire.html"},
  { name:"Doodle Halloween Momo Cat : Academy", category:["Google Doodle"], image:"images/gameicons/Doodle Halloween Momo Cat : Academy.avif", link:"Doodle Halloween Momo Cat : Academy.html"},
  { name:"Kingdom Defender - Tower Defense", category:["Defense Game", "Strategy Games"], image:"images/gameicons/Kingdom Defender - Tower Defense.avif", link:"Kingdom Defender - Tower Defense.html"},
  { name:"Mahjong Unlimited", category:["Puzzle"], image:"images/gameicons/Mahjong Unlimited.avif", link:"Mahjong Unlimited.html"},
  { name:"Obby: Click and Grow", category:["Obby"], image:"images/gameicons/Obby: Click and Grow.avif", link:"Obby Click and Grow.html"},
  { name:"Tower Defense", category:["Defense Game", "Strategy Games"], image:"images/gameicons/Tower Defense.avif", link:"Tower Defense.html"},
  { name:"2 Player Games Mini Games", category:["."], image:"images/gameicons/2 Player Games Mini Games.avif", link:"2 Player Games Mini Games.html"},
  { name:"Dark Boy", category:["."], image:"images/gameicons/Dark Boy.avif", link:"Dark Boy.html"},
  { name:"Doodle Boba Bubble Tea", category:["."], image:"images/gameicons/Doodle Boba Bubble Tea.avif", link:"Doodle Boba Bubble Tea.html"},
  { name:"Doodle Halloween Momo Cat : Sea Magic", category:["."], image:"images/gameicons/Doodle Halloween Momo Cat : Sea Magic.avif", link:"Doodle Halloween Momo Cat : Sea Magic.html"},
  { name:"Fun With Flags - Ultimate Quiz Game", category:["."], image:"images/gameicons/Fun With Flags - Ultimate Quiz Game.avif", link:"Fun With Flags - Ultimate Quiz Game.html"},
  { name:"Homo Evolution", category:["."], image:"images/gameicons/Homo Evolution.avif", link:"Homo Evolution.html"},
  { name:"Moon Chess", category:["."], image:"images/gameicons/Moon Chess.avif", link:"Moon Chess.html"},
  { name:"Plants Vs Steal Brainrots", category:["."], image:"images/gameicons/Plants Vs Steal Brainrots.avif", link:"Plants Vs Steal Brainrots.html"},
  { name:"Shadow Stick Ninja", category:["."], image:"images/gameicons/Shadow Stick Ninja.avif", link:"Shadow Stick Ninja.html"},
  { name:"Snake to Eat", category:["."], image:"images/gameicons/Snake to Eat.avif", link:"Snake to Eat.html"},
  { name:"Archer Ragdoll", category:["."], image:"images/gameicons/Archer Ragdoll.avif", link:"Archer Ragdoll.html"},
  { name:"Climb Up", category:["."], image:"images/gameicons/Climb Up.avif", link:"Climb Up.html"},
  { name:"Fishing Frenzy", category:["."], image:"images/gameicons/Fishing Frenzy.avif", link:"Fishing Frenzy.html"},
  { name:"Hard Working Man", category:["."], image:"images/gameicons/Hard Working Man.avif", link:"Hard Working Man.html"},
  { name:"Hedgies", category:["."], image:"images/gameicons/Hedgies.avif", link:"Hedgies.html"},
  { name:"Idle Supermarket Tycoon", category:["."], image:"images/gameicons/Idle Supermarket Tycoon.avif", link:"Idle Supermarket Tycoon.html"},
  { name:"Knife Smash", category:["."], image:"images/gameicons/Knife Smash.avif", link:"Knife Smash.html"},
  { name:"Men vs Gorillas", category:["."], image:"images/gameicons/Men vs Gorillas.avif", link:"Men vs Gorillas.html"},
  { name:"MR RACER - Car Racing", category:["."], image:"images/gameicons/MR RACER - Car Racing.avif", link:"MR RACER - Car Racing.html"},
  { name:"Nuts Bolts Sort", category:["."], image:"images/gameicons/Nuts Bolts Sort.avif", link:"Nuts Bolts Sort.html"},
  { name:"Obby: +1 Jump per Click", category:["."], image:"images/gameicons/Obby: +1 Jump per Click.avif", link:"Obby Jump per Click.html"},
  { name:"Obby: Mini-Games", category:["."], image:"images/gameicons/Obby: Mini-Games.avif", link:"Obby Mini-Games.html"},
  { name:"Police Chase Simulator", category:["."], image:"images/gameicons/Police Chase Simulator.avif", link:"Police Chase Simulator.html"},
  { name:"Red and Blue Snipers", category:["."], image:"images/gameicons/Red and Blue Snipers.avif", link:"Red and Blue Snipers.html"},
  { name:"Rooftop Run", category:["."], image:"images/gameicons/Rooftop Run.avif", link:"Rooftop Run.html"},
  { name:"RPG Idle Clicker", category:["."], image:"images/gameicons/RPG Idle Clicker.avif", link:"RPG Idle Clicker.html"},
  { name:"Screw Match", category:["."], image:"images/gameicons/Screw Match.avif", link:"Screw Match.html"},
  { name:"Sniper Attack2", category:["."], image:"images/gameicons/Sniper Attack2.avif", link:"Sniper Attack2.html"},
  { name:"Wood Blocks Jam", category:["."], image:"images/gameicons/Wood Blocks Jam.avif", link:"Wood Blocks Jam.html"},
  { name:"Word Search Hidden Words", category:["."], image:"images/gameicons/Word Search Hidden Words.avif", link:"Word Search Hidden Words.html"},
  { name:"chess multiplayer", category:["Multiplayer Games", "Board Games", "Strategy Games"], image:"images/gameicons/chess multiplayer.jpg", link:"chess multiplayer.html"},
  { name:"Dinosaur", category:["."], image:"images/gameicons/dinosaur-game.jpg", link:"dinosaur.html"},
  { name:"Donkey Kong", category:["Monkey Games", "Action Games"], image:"images/gameicons/donkey-kong.jpg", link:"donkey-kong.html"},
  { name:"Doodle Champion Island", category:["Sport", "Google Doodle"], image:"images/gameicons/doodle-champion-island.jpg", link:"island.html"},
  { name:"Drunken Boxing", category:["Sport", "Boxing Games", "Multiplayer Games"], image:"images/gameicons/drunken boxing.jpg", link:"drunken boxing.html"},
  { name:"Fall Guys", category:["Multiplayer Games", "Parkour Games"], image:"images/gameicons/fall guys.jpg", link:"fall guys.html"},
  { name:"fireboy and watergirl", category:["Multiplayer Games"], image:"images/gameicons/fireboy and watergirl.jpg", link:"fireboy and watergirl.html"},
  { name:"Flappy Bird", category:["."], image:"images/gameicons/flappy-bird.jpg1.jpeg", link:"flappybird.html"},
  { name:"Scary Granny", category:["Horror"], image:"images/gameicons/scary granny.jpg", link:"scary granny.html"},
  { name:"goal io", category:["Football Games", "Sport", "io games"], image:"images/gameicons/goal io.jpg", link:"goal io.html"},
  { name:"Gorilla Multiplayer", category:["Multiplayer Games", "Monkey Games"], image:"images/gameicons/gorilla multiplayer.jpg", link:"gorilla multiplayer.html"},
  { name:"noob vs pro lava", category:["Multiplayer Games", "Parkour Games", "Minecraft"], image:"images/gameicons/noob vs pro lava.jpg", link:"noob vs pro lava.html"},
  { name:"Poker", category:["Multiplayer Games", "Gambling Games"], image:"images/gameicons/poker.jpg", link:"poker.html"},
  { name:"Mathai's Tea Shop", category:["Idle Games", "Shop"], image:"images/gameicons/Mathai's Tea Shop.webp", link:"Mathai's Tea Shop.html"},
  { name:"Dodge Clicker", category:["Idle Games"], image:"images/gameicons/Doge Clicker.webp", link:"Doge Clicker.html"},
  { name:"Russian Knife Roulette Game", category:["Action Games"], image:"images/gameicons/Russian Knife Roulette Game.webp", link:"Russian Knife Roulette Game.html"},
  { name:"PacFruit Ninjaman", category:["Action Games", "Fruit"], image:"images/gameicons/Fruit Ninja.webp", link:"Fruit Ninja.html"},
  { name:"Helix jump", category:["Parkour Games"], image:"images/gameicons/Helix jump.webp", link:"Helix jump.html"},
  { name:"Galactic Wars", category:["War Games"], image:"images/gameicons/Galactic Wars.webp", link:"Galactic Wars.html"},
  { name:"Sudoku challenge", category:["Puzzle"], image:"images/gameicons/Sudoku challenge.webp", link:"Sudoku challenge.html"},
  { name:"The Life Of Happy Stoner", category:["Stoner"], image:"images/gameicons/The Life Of Happy Stoner.webp", link:"The Life Of Happy Stoner.html"},
  { name:"Trolling Indian Scammers", category:["."], image:"images/gameicons/Trolling Indian Scammers.webp", link:"Trolling Indian Scammers.html"},
  { name:"Weed Smoking Simulator", category:["Stoner"], image:"images/gameicons/Weed Smoking Simulator.webp", link:"Weed Smoking Simulator.html"},
  { name:"Fill the cup", category:["Puzzle"], image:"images/gameicons/Fill the cup.webp", link:"Fill the cup.html"},
  { name:"Cat Bubble Shooter", category:["Shooting Games"], image:"images/gameicons/Cat Bubble Shooter.webp", link:"Cat Bubble Shooter.html"},
  { name:"Bird Sniper 2 Demo", category:["Action Games", "Shooting Games"], image:"images/gameicons/Bird Sniper 2 Demo.webp", link:"Bird Sniper 2 Demo.html"},
  { name:"Bulb connector", category:["Puzzle"], image:"images/gameicons/Bulb connector.webp", link:"Bulb connector.html"},
  { name:"World Dictator", category:["."], image:"images/gameicons/World Dictator.webp", link:"World Dictator.html"},
  { name:"Kill Baby Hitler", category:["Hitler", "Action Games"], image:"images/gameicons/Kill Baby Hitler.webp", link:"Kill Baby Hitler.html"},
  { name:"Where in Space is Baby Hitler", category:["Hitler", "Action Games"], image:"images/gameicons/Where in Space is Baby Hitler.webp", link:"Where in Space is Baby Hitler.html"},
];